#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 24, 2024 08:45:02 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import main_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class mainFrame:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("320x380+324+141")
        top.minsize(120, 1)
        top.maxsize(3844, 1181)
        top.resizable(0,  0)
        top.title("Robohash Gatti")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.dlButton = tk.Button(self.top)
        self.dlButton.place(x=10, y=338, height=26, width=300)
        self.dlButton.configure(activebackground="#d9d9d9")
        self.dlButton.configure(activeforeground="black")
        self.dlButton.configure(background="#d9d9d9")
        self.dlButton.configure(disabledforeground="#a3a3a3")
        self.dlButton.configure(foreground="#000000")
        self.dlButton.configure(highlightbackground="#d9d9d9")
        self.dlButton.configure(highlightcolor="#000000")
        self.dlButton.configure(text='''Download''')

        self.nameEntry = tk.Entry(self.top)
        self.nameEntry.place(x=10, y=310, height=20, width=300)
        self.nameEntry.configure(background="white")
        self.nameEntry.configure(disabledforeground="#a3a3a3")
        self.nameEntry.configure(font="TkFixedFont")
        self.nameEntry.configure(foreground="#000000")
        self.nameEntry.configure(highlightbackground="#d9d9d9")
        self.nameEntry.configure(highlightcolor="#000000")
        self.nameEntry.configure(insertbackground="#000000")
        self.nameEntry.configure(selectbackground="#d9d9d9")
        self.nameEntry.configure(selectforeground="black")

        self.imgCanvas = tk.Canvas(self.top)
        self.imgCanvas.place(x=10, y=10, height=300, width=300)
        self.imgCanvas.configure(background="#d9d9d9")
        self.imgCanvas.configure(borderwidth="2")
        self.imgCanvas.configure(highlightbackground="#d9d9d9")
        self.imgCanvas.configure(highlightcolor="#000000")
        self.imgCanvas.configure(insertbackground="#000000")
        self.imgCanvas.configure(relief="ridge")
        self.imgCanvas.configure(selectbackground="#d9d9d9")
        self.imgCanvas.configure(selectforeground="black")

def start_up():
    main_support.main()

if __name__ == '__main__':
    main_support.main()




